main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Skills
    url: '#skills'
    weight: 20
  - name: Experience
    url: '#experience'
    weight: 30
  - name: Accomplishments
    url: '#accomplishments'
    weight: 40
  - name: Projects
    url: '#projects'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  - name: CV
    url: uploads/resume.pdf
    weight: 70


